services:
  caddy:
    image: docker.io/library/caddy:2.10.0-alpine
    restart: unless-stopped
    ports:
      - 8443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./cert.pem:/cert.pem:Z
      - ./cert.key:/cert.key:Z

  ui:
    image: panel/ui:latest
    build:
      context: ./ui
    restart: unless-stopped

  api:
    image: panel/api:latest
    build:
      context: ./api
    restart: unless-stopped
    user: root
    environment:
      - PANEL_SERVER_HOST=ayeama.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - api_data:/app

volumes:
  api_data:
