FROM node:25.8.1 AS build

WORKDIR /app

COPY web/package.json web/package-lock.json ./
RUN npm install

COPY web/ .
RUN npm run build

FROM nginx:1.29.6

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/.output/public /usr/share/nginx/html
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
