FROM docker.io/library/golang:1.25.6-trixie AS builder-backend

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=1 go build -o panel cmd/panel/main.go

FROM docker.io/library/debian:trixie-slim AS backend

WORKDIR /app

COPY --from=builder-backend /app/panel /usr/bin/panel

EXPOSE 8000

CMD ["panel"]
