FROM docker.io/library/node:24.13.0-trixie AS builder-frontend

WORKDIR /app

COPY web/package.json web/package-lock.json .

RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY web/ .

RUN npm run build

FROM docker.io/nginxinc/nginx-unprivileged:1.31.2-trixie

COPY web/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder-frontend /app/dist /usr/share/nginx/html
