services:
  nginx:
    image: docker.io/library/nginx:1.28.0-alpine
    ports:
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/panel.conf:z
      - ./.htpasswd:/.htpasswd:z
      - ./cert.pem:/cert.pem:z
      - ./cert.key:/cert.key:z

  ui:
    image: localhost/panel/ui:latest
    build:
      context: ./ui
    security_opt:
      - label=disable

  api:
    image: localhost/panel/api:latest
    build:
      context: ./api
    userns_mode: keep-id:uid=42873,gid=42873
    environment:
      - PANEL_SERVER_HOST=ayeama.com
      - PANEL_RUNTIME_URI=unix:${XDG_RUNTIME_DIR}/podman/podman.sock
    ports:
      - 8000:8000
    volumes:
      - api_data:/data
      - ${XDG_RUNTIME_DIR}/podman:${XDG_RUNTIME_DIR}/podman:Z
    security_opt:
      - label=disable

  debug:
    image: docker.io/library/busybox
    command: sleep 999999

volumes:
  api_data:
