services:
  frontend:
    image: panel-frontend
    build:
      dockerfile: Dockerfile.frontend
  
  backend:
    image: panel-backend
    build:
      dockerfile: Dockerfile.backend
    volumes:
      - "/run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:Z"
