---
- name: Deploy
  hosts: all
  gather_facts: true
  tasks:
    - name: Create pod
      containers.podman.podman_pod:
        state: quadlet
        name: panel
        ports:
          - 8442:8442
          - 8443:8443
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target

    - name: Create api container
      containers.podman.podman_container:
        state: quadlet
        pod: panel.pod
        name: panel-api
        image: panel-backend:latest
        volume:
          - "%t/podman/podman.sock:/run/user/1000/podman/podman.sock"
        security_opt:
          - label=disable

    - name: Create ui container
      containers.podman.podman_container:
        state: quadlet
        pod: panel.pod
        name: panel-ui
        image: panel-frontend:latest

    - name: Copy caddy configuration file
      ansible.builtin.template:
        src: templates/Caddyfile.j2
        dest: "{{ ansible_facts['user_dir'] }}/Caddyfile"

    - name: Create caddy container
      containers.podman.podman_container:
        state: quadlet
        pod: panel.pod
        name: panel-caddy
        image: docker.io/caddybuilds/caddy-cloudflare:latest
        volume:
          - "%h/Caddyfile:/etc/caddy/Caddyfile:Z"

    - name: Reload systemd
      ansible.builtin.systemd_service:
        scope: user
        daemon_reload: true
    
    - name: Start pod
      ansible.builtin.systemd_service:
        scope: user
        state: restarted
        enabled: true
        name: panel-pod
    
    - name: Start api container
      ansible.builtin.systemd_service:
        scope: user
        state: restarted
        enabled: true
        name: panel-api
    
    - name: Start ui container
      ansible.builtin.systemd_service:
        scope: user
        state: restarted
        enabled: true
        name: panel-ui
    
    - name: Start caddy container
      ansible.builtin.systemd_service:
        scope: user
        state: restarted
        enabled: true
        name: panel-caddy
