---
- name: Deploy
  hosts: all
  gather_facts: true
  tasks:
    - name: Create pod
      containers.podman.podman_pod:
        state: quadlet
        name: panel
        ports:
          - 8442:8442
          - 8443:8443
        quadlet_options:
          - |
            [Install]
            WantedBy=default.target

    - name: Create api container
      containers.podman.podman_container:
        state: quadlet
        pod: panel.pod
        name: panel-api
        image: panel-backend:latest
        volume:
          - "%t/podman/podman.sock:/run/user/1000/podman/podman.sock"
        security_opt:
          - label=disable

    - name: Create ui container
      containers.podman.podman_container:
        state: quadlet
        pod: panel.pod
        name: panel-ui
        image: panel-frontend:latest

    - name: Copy caddy configuration file
      ansible.builtin.copy:
        src: files/Caddyfile
        dest: "{{ ansible_facts['user_dir'] }}/Caddyfile"

    - name: Copy caddy certificate file
      ansible.builtin.copy:
        src: files/server.crt
        dest: "{{ ansible_facts['user_dir'] }}/server.crt"

    - name: Copy caddy certificate key file
      ansible.builtin.copy:
        src: files/server.key
        dest: "{{ ansible_facts['user_dir'] }}/server.key"

    - name: Create caddy container
      containers.podman.podman_container:
        state: quadlet
        pod: panel.pod
        name: panel-caddy
        image: caddy:latest
        volume:
          - "%h/Caddyfile:/etc/caddy/Caddyfile:Z"
          - "%h/server.crt:/etc/caddy/certs/server.crt:Z"
          - "%h/server.key:/etc/caddy/certs/server.key:Z"

    - name: Reload systemd
      ansible.builtin.systemd_service:
        scope: user
        daemon_reload: true
    
    - name: Start pod
      ansible.builtin.systemd_service:
        scope: user
        state: started
        enabled: true
        name: panel-pod
    
    - name: Start api container
      ansible.builtin.systemd_service:
        scope: user
        state: started
        enabled: true
        name: panel-api
    
    - name: Start ui container
      ansible.builtin.systemd_service:
        scope: user
        state: started
        enabled: true
        name: panel-ui
    
    - name: Start caddy container
      ansible.builtin.systemd_service:
        scope: user
        state: started
        enabled: true
        name: panel-caddy
