FROM ghcr.io/pumpkin-mc/pumpkin:master

LABEL com.github.ayeama.panel.image.id="60d49f1d-de30-4e5c-9a61-3b0e76f135cf"
LABEL com.github.ayeama.panel.image.version="1"
LABEL com.github.ayeama.panel.image.name="Minecraft"
LABEL com.github.ayeama.panel.image.variant="Pumpkin"
LABEL com.github.ayeama.panel.image.release="latest"
LABEL com.github.ayeama.panel.image.description=""

WORKDIR /pumpkin

EXPOSE 25565/tcp

VOLUME /pumpkin
